### ISSUE TITLE
Support for cover

### ISSUE THREAD

**Issue by bapt** [kaworu/tagutil#38]
Not sure if I missed the obvious, but I can't find a way to add cover tags.

**Comment by kaworu** [comment]
Hey @bapt, long time no see :smiley:

You can add arbitrary tags (when the file format support them, e.g. ogg of flac) with `tagutil set:cover=foo` but I'm guessing you wish the cover data to be retrieved automatically?

**Comment by bapt** [comment]
yes, your guess is right, I add willing to be able to tagutil set:cover=foo.jpg transparently.

**Comment by kaworu** [comment]
I remember trying to do this before and gave up, both because it's a non-trivial feature and also because I wish to keep it as simple as possible (so much so that features were removed, e.g. [filter](https://github.com/kaworu/tagutil/commit/3ab6170471dcc6c4b984b123776ca60acb93d3ee)).

Nowadays I think most "advance features" should be wrapper scripts (see https://github.com/kaworu/tagutil/tree/master/scripts) including this one. What do you think?
